### ISSUE TITLE
[fix] 위니 피드 / swipe refresh 스크롤 위치 문제 해결

### ISSUE THREAD

**Issue by sxunea** [team-winey/Winey-AOS#181]
## 💡 ISSUE
swipe refresh 후에도 스크롤 위치를 기억해 재조정되는 문제 해결

## 📌 TO DO
- [x] 스크롤 위치 초기화

**Comment by leeeha** [comment]
이미 출시 버튼을 눌러서 이 부분은 다음 버전에 반영해야 될 거 같아요! 
저도 사용하면서 발견했던 이슈인데 일부러 의도한 건가 싶어서 얘기를 안 꺼냈네요 😅
