### ISSUE TITLE
[fix] 위니피드, 마이피드 / 스크롤 위치가 제대로 복원되지 않는 이슈

### ISSUE THREAD

**Issue by leeeha** [team-winey/Winey-AOS#192]
## 💡 ISSUE

위니피드에서 상세피드로 갔다가 다시 돌아올 때, 스크롤 위치가 제대로 복원되지 않는 문제가 발생했다. 

**Problem 1. 위니피드 리스트를 여러 번 호출** 

- 로그를 자세히 찍어보니까, 스크롤 위치를 복원하는 restoreScrollPosition 함수가 불필요하게 여러 번 호출되는 현상을 발견했다. 
- 이미 initGetFeedStateObserver 함수에서 getWineyFeedListState를 관찰하여 restoreScrollPosition 함수를 호출하는데, 이것과 중복해서 불필요하게 onStart 함수에서 getWineyFeed 함수를 다시 호출하고 있었다. 

**Problem 2. not loading 상태일 때 스크롤 위치 조정**

- 로딩 완료 뿐만 아니라, 로딩이 되고 있지 않은 상태에서도 `LoadState.NotLoading` 상태인데 그때마다 restoreScrollPosition 함수가 호출되어 이전에 selectedItemIndex 변수에 저장해둔 그 위치로 스크롤이 되돌아가려고 하는 문제가 발생했다. 
- 상세피드에서 위니피드로 돌아와서 스크롤 위치를 복원한 다음에는 selectedItemIndex 변수를 -1로 초기화 하여, 원치 않는 위치로 스크롤이 되돌아 가버리는 문제를 해결했다.

**Comment by sxunea** [comment]
## 📝  TroubleShooting

- loadState.NotLoading에 해당하는 케이스를 정확하게 알지못하고 처리해 발생했던 이슈이다
- loadState.NotLoading indicates the [PagingData](https://developer.android.com/reference/kotlin/androidx/paging/PagingData) is not currently loading, and no error currently observed
- 이렇게 오류가 안나면서, 현재 로딩중이지 않은 모든 상태를 NotLoading으로 취급하는데, 이전에는 NotLoading을 로딩 완료의 상태로만 취급해 구현했다. 하지만, 스크롤 위치 복원이 완료된 후에도 NotLoading 상태가 되는 상황이 발생하면 저장해둔 스크롤 위치로 다시 조정되는 오류가 발생했다. 따라서 처음 스크롤 위치 복원을 하고 난 다음 selectedItemIndex을 초기화 해줘 다시 복원해주는 상황을 방지했다

**Comment by sxunea** [comment]
📝 TroubleShooting
상세페이지의 변경사항을 반영하기 위해 다음과 같은 방법을 시도했지만 각각 문제가 있었다
    -  onStart()에 viewModel.getWineyFeed() : getWineyFeedState가 계속 관찰되어 restoreScrollPosition 중복 호출
    -  onStart()에 wineyFeedAdapter.refresh() : 한 페이지를 새로 불러오기 때문에 비용이 커 시간 소요됨. 사용자에게 빈화면 꽤 오랜시간 노출

**상세페이지를 다녀올때 변경사항이 반영되고, 스크롤위치가 유지되어야 하며, 사용자에게는 매끄러운 사용감을 제공하기 위해**
onStart에 변경사항이 생긴 피드의 상세페이지 내용을 불러 어댑터에서 update 시켜줌
