### ISSUE TITLE
[add] 기초 세팅 / 앱 경량화, 난독화

### ISSUE THREAD

**Issue by sxunea** [team-winey/Winey-AOS#208]
## 💡 ISSUE
- build.gradle에 앱 축소, 난독화 코드 추가

## 📌 TO DO
- [x] isMinifyEnabled = true
- [x] isShrinkResources = true

## 🔍 REFRENCE 
[공식문서_난독화,최적화,축소](https://developer.android.com/studio/build/shrink-code?hl=ko#configuration-files), [R8 Compiler](https://thinking-face.tistory.com/entry/Android-%EC%95%B1-%EA%B2%BD%EB%9F%89%ED%99%94-with-R8)

**Comment by leeeha** [comment]
오호 이런 설정도 있었군요!! 😮😮
