### ISSUE TITLE
[fix] 카카오 로그인 오류 수정

### ISSUE THREAD

**Issue by Sangwook123** [team-winey/Winey-AOS#218]
## 💡 ISSUE

java.lang.ClassCastException? 객체를 잘못된 클래스로 캐스팅할 때 발생하는 예외
의존성 주입중에 UserApiClient를 클래스의 인스턴스로 캐스팅하는 과정에서 발생한 것으로 추정합니다 ! 

## 📌 TO DO

- [x] Hilt로 제공하던 kakaologinservice datasource에서 직접 구현, UserApiClient 클래스캐스팅 오류 가능성 해결
- [x] Proguard룰 추가

**Comment by leeeha** [comment]
todo 부분 내용 채워주면 좋을 거 같아요! :)
