### ISSUE TITLE
[fix] 마이페이지 / 2주 절약, 소비 애니메이션 깜빡임 현상 개선

### ISSUE THREAD

**Issue by sxunea** [team-winey/Winey-AOS#275]
## 📌 TO DO

- [x] 원인 파악 후 깜빡임 현상 제거

## 💥 어떤 버그가 발생했나요?
사용자의 스크롤 위치가 텍스트뷰가 완전히 볼 수 있는 상태에 다다를 때 (즉, 그래프 상자의 윗변과 아래변를 다 볼 수 있을때) 애니메이션을 시작하도록 로직을 구현했다. 

## 🤷‍♀️ 왜 발생했나요?
애니메이션이 실행될 수 있는 조건인 위치에 계속 머무르면, animator.start()가 계속 실행되는 것이 원인이다. 애니메이션이 종료되기도 전에 시작되면서 드문 경우에 사용자가 보기에 그래프가 깜빡이는 것처럼 보였다.

## 🤔 어떻게 해결했나요?
isAnimating이라는 플래그를 만들어, 애니메이션이 끝난경우 animator.start의 재실행을 방지했다.

## 더 나은 방법은 없을까요? (추가 개선기)
isAnimating을 도입하니 모든 textView(그래프 상자)가 해당 플래그를 사용하므로 가끔가다 각 애니메이션이 독립적으로 관리되지 못했다. 
예) tv1의 애니메이션이 시작되어 true이고, 종료 전인데 tv2의 애니메이션이 시작될 위치에 도달하면 여전히 해당 플래그가 true이므로 애니메이션이 시작되지 않는다 -> 따라서 각 textView를 boolean과 함께 map으로 관리해 애니메이션의 running여부를 관리해 다시 한번 개선했다.

-> 일단은 이렇게 개선했고, 이전의 현상은 모두 나타나지 않습니다. 다만 이를 직접 변수를 생성해 상태를 관리하기보다는 animator의 속성을 이용해 하는 방법도 있는지 배포랑 시험 끝나고 한번 더 봐볼게요 ! (isRunning, isCanceled 등등)

**Comment by leeeha** [comment]
트러블슈팅 템플릿 만들어둔 거 활용해서 넘 좋네요 🫶
